In [17]:
import numpy as np
a=3; b=8; c=5-1j; d=2+7*1j
A=np.array([[ a,d,d.conjugate()],
          [ d,c,b ],
    [d.conjugate(),b,c.conjugate()]])
A

array([[3.+0.j, 2.+7.j, 2.-7.j],
       [2.+7.j, 5.-1.j, 8.+0.j],
       [2.-7.j, 8.+0.j, 5.+1.j]])

In [2]:
X=np.array( [[1,0,0],
             [0,0,1],
             [0,1,0]] )

XT.A.X=As

In [18]:
np.dot(np.dot(X.transpose(),A),X)

array([[3.+0.j, 2.-7.j, 2.+7.j],
       [2.-7.j, 5.+1.j, 8.+0.j],
       [2.+7.j, 8.+0.j, 5.-1.j]])

In [20]:
Ainv=np.linalg.inv(A)
Ainv.round(3)

array([[-0.031-0.j   ,  0.01 -0.075j,  0.01 +0.075j],
       [ 0.01 -0.075j,  0.048+0.025j,  0.023+0.j   ],
       [ 0.01 +0.075j,  0.023-0.j   ,  0.048-0.025j]])

In [22]:
np.dot(np.dot(X.transpose(),Ainv),X).round(3)

array([[-0.031-0.j   ,  0.01 +0.075j,  0.01 -0.075j],
       [ 0.01 +0.075j,  0.048-0.025j,  0.023-0.j   ],
       [ 0.01 -0.075j,  0.023+0.j   ,  0.048+0.025j]])

In [7]:
np.dot(A,Ainv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [14]:
d=1j
d.conjugate()

-1j